Don't play additional samples when already playing one
agrande/lba2remake pull request #561
Opened 2021-05-01 14:32 UTC by slwilliams

This changes to keep track of samples on a per actor basis i.e. we allow the same sample to be concurrently played but only once per actor. This allows two enemies to shoot at the same time with the same sample and we'll hear both, but in the case of the jetpack we don't play that sample twice since it's the same actor (Twinsen).

This doesn't change the 3D positional audio stuff, need to look at that some more. We also still aren't looping samples correctly (there's still a slight gap at the end of the jetpack sample playback, still trying to work out how best to resolve that.

I've also fixed the case where we end up with the theme music playing twice at the same time which has been annoying me for a while.

2021-05-01 15:05 UTC, xesf requested changes

2021-05-01 15:05 UTC, xesf commented on src/audio/index.ts
> +            samplesPerActor[actorIndex][index] = sampleSource;
Looking at this it just made me realise the issue Adrian notice in VR may be caused by this.

Both samples and samplesPerActor are never released. The more we play, the more samples both objects will be referencing. The decoded sample is cached in 

I will suggest to create a release function that will delete the contents of these objects and called during scene change in the Scene Manager release function.

2021-05-01 17:35 UTC, xesf commented
> We also still aren't looping samples correctly (there's still a slight gap at the end of the jetpack sample playback, still trying to work out how best to resolve that.
Those are triggered per animation frame.
Perhaps we are not stopping the previous sample before starting the new one.

2021-05-01 20:04 UTC, agrande approved these changes

2021-05-02 21:03 UTC, xesf approved these changes
I've approved so we can merge it.
I will do the sample release based on my comments.

2021-05-02 21:04 UTC, merged