Implement the 'set_sprite' opcode
agrande/lba2remake pull request #645
Opened 2021-09-28 23:49 UTC by fraserjgordon

This updates the sprite of the actor to the one with the given index.

To test, go to Twinsen's neighbour's house and set the value of game var 66 (with #644  it is called 'sewer_map_state') to a value >= 1 (`GALLIC_ACID_USED`) and the map on the desk will immediately update with the new sprite. To go back to the original sprite, the var needs to be set to 0 and the scene exited (as the life script for the map stops running after updating the sprite).

This also works for the various switches in the world (e.g. in Lupin-Bourg's sewers).

2021-09-28 23:50 UTC, fraserjgordon commented on src/game/scripting/life.ts
> +    this.actor.reloadModel(this.scene);
I know nothing about async JS programming so I'm not sure if calling the async `reloadModel` method like this is sound but it does seem to work in my testing...

2021-09-29 09:49 UTC, xesf requested changes

2021-09-29 09:49 UTC, xesf commented on src/game/scripting/life.ts
> +    this.actor.reloadModel(this.scene);
That is fine, we don't need to wait for the reload to proceed with the script.

You should await if you want to wait for the results of the async function, but also it is require to have at least 1 await inside an async function (in this case set_sprite is not async.

2021-09-29 09:49 UTC, xesf commented on src/game/scripting/life.ts
> +    this.actor.reloadModel(this.scene);
In terms of the code, you can actually use [setSprite](https://github.com/agrande/lba2remake/blob/308654bcd038447a1900c45d7f06fe41962be965/src/game/Actor.ts#L623) from the actor itself so you won't duplicate the code. There are extra validations there as well so it will be safer to use it instead.

2021-09-29 19:16 UTC, agrande approved these changes
Lgtm, besides the change @xesf suggested.

2021-09-29 19:16 UTC, agrande commented on src/game/scripting/life.ts
> +export function SET_SPRITE(this: ScriptContext, id) {
Maybe add a type annotation on the id param.
Not strictly needed, but preferable in general to add type to function params.

2021-09-29 22:27 UTC, fraserjgordon commented on src/game/scripting/life.ts
> +    this.actor.reloadModel(this.scene);
Done

2021-09-29 22:27 UTC, fraserjgordon commented on src/game/scripting/life.ts
> +export function SET_SPRITE(this: ScriptContext, id) {
Done.

2021-09-30 08:41 UTC, xesf approved these changes

2021-10-01 15:46 UTC, merged